apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
spec:
  template:
    spec:
      containers:
      - name: my-app-2
        env:
          - name: foo
            value: we-are-in-dev
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: credentials
